[FIX] snailmail_account: consider valid invoices with partner
Before this commit there would be traceback on sending Invoice without `partner_id` field due to computing `_is_valid_address`.

Issue:
   Upload New Customer Invoice (Which creates new Invoice without `partner_id`)
   Switch to list view
   Select Invoice and Send & print

Traceback:
    ValueError: Expected singleton: res.partner()


With this commit we will consider Invoices having `partner_id`